name: io_2014_contacts_demo
version: 0.0.2+2
author: Kevin Moore <kevmoo+github@google.com>
description: Dart, Polymer, Paper Sample App from Google IO 2014
homepage: https://github.com/kevmoo/io_2014_contacts_demo
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  paper_elements: '>=0.3.0 <0.4.0'
  polymer: '>=0.14.3 <0.15.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
